### ISSUE TITLE
Signal as default pin name

### ISSUE THREAD

**Issue by dzarda** [yaqwsx/Pinion#10]
The template command uses the signal name only as a comment. A better solution would be to apply it directly as the pin name. This maximizes the usability even without human interaction.

👍 
```yml
            '3':
                name: STM-I2C-SCL
                description: ''
                groups: []
```

👎  
```yml
            '3': # Connected to STM-I2C-SCL
                name: IM4.3
                description: ''
                groups: []
```
